import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useIncidentStore } from '../store'
import { FileText, Download, CheckCircle2, Loader2 } from 'lucide-react'

function generateReportContent(incident: ReturnType<typeof useIncidentStore['getState']>['incidents'][0] | null): string {
  if (!incident) return 'No active incident found.'
  const now = new Date().toLocaleString()
  const detection = incident.detection
  const risk = incident.risk
  const impact = incident.impact
  const recs = incident.ai_recommendations ?? []

  return `
FIREGUARD NEXUS — INCIDENT REPORT
==================================
Generated: ${now}
Incident ID: ${incident.id}
Status: ${incident.status ?? 'ACTIVE'}
Severity: ${incident.severity ?? 'HIGH'}

──────────────────────────────────
1. DETECTION SUMMARY
──────────────────────────────────
Location: ${detection?.location_name ?? 'Unknown'}
Coordinates: ${detection ? `${detection.lat.toFixed(4)}°N, ${detection.lng.toFixed(4)}°E` : '—'}
Detection Time: ${detection?.timestamp ? new Date(detection.timestamp).toLocaleString() : '—'}
Confidence: ${detection ? `${(detection.confidence * 100).toFixed(1)}%` : '—'}
Source: ${detection?.source ?? '—'}
Area: ${detection?.area_ha ? `${detection.area_ha.toFixed(1)} hectares` : '—'}

──────────────────────────────────
2. RISK ANALYSIS
──────────────────────────────────
Risk Score: ${risk ? `${risk.score.toFixed(0)}/100` : '—'}
Danger Level: ${risk?.danger_level ?? '—'}
Wind Speed: ${risk?.weather_data?.wind_speed ? `${risk.weather_data.wind_speed.toFixed(0)} km/h` : '—'}
Temperature: ${risk?.weather_data?.temperature ? `${risk.weather_data.temperature.toFixed(0)}°C` : '—'}
Humidity: ${risk?.weather_data?.humidity ? `${risk.weather_data.humidity.toFixed(0)}%` : '—'}

──────────────────────────────────
3. AI RECOMMENDATIONS
──────────────────────────────────
${recs.length > 0 ? recs.map(r => `[${r.priority}] ${r.action}\n  Reason: ${r.reason}`).join('\n\n') : 'No recommendations available.'}

──────────────────────────────────
4. IMPACT ASSESSMENT
──────────────────────────────────
Trees Lost: ${impact?.trees_lost?.toLocaleString() ?? '—'}
Wildlife Affected: ${impact?.wildlife_affected?.toLocaleString() ?? '—'}
CO₂ Emissions: ${impact?.co2_tons?.toLocaleString() ?? '—'} tons
Economic Damage: ${impact ? `NPR ${(impact.dollar_damage / 1_000_000).toFixed(2)}M` : '—'}
Population Affected: ${impact?.population_affected?.toLocaleString() ?? '—'}
Buildings Threatened: ${impact?.structures_threatened?.toLocaleString() ?? '—'}

──────────────────────────────────
5. TIMELINE
──────────────────────────────────
${(incident.timeline ?? []).map(e => `${new Date(e.timestamp).toLocaleTimeString()} — ${e.title}: ${e.description}`).join('\n') || 'No timeline events recorded.'}

──────────────────────────────────
END OF REPORT — FireGuard Nexus v2
Report generated by AI Commander
  `.trim()
}

export const ReportGenerator: React.FC = () => {
  const incident = useIncidentStore((s) => s.getActiveIncident())
  const [isGenerating, setIsGenerating] = useState(false)
  const [report, setReport] = useState<string | null>(null)
  const [generated, setGenerated] = useState(false)

  const handleGenerate = async () => {
    setIsGenerating(true)
    setReport(null)
    await new Promise(r => setTimeout(r, 2200))
    setReport(generateReportContent(incident))
    setIsGenerating(false)
    setGenerated(true)
  }

  const handleDownload = () => {
    if (!report) return
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `fireguard-report-${incident?.id ?? 'incident'}-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="bg-gradient-to-r from-emerald-900/40 to-teal-900/40 border border-emerald-700/50 rounded-xl p-4 mb-4 flex-shrink-0">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-emerald-500/20 rounded-lg border border-emerald-500/30">
            <FileText size={20} className="text-emerald-300" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-emerald-200">Report Generator</h2>
            <p className="text-xs text-emerald-400">Auto AI incident report</p>
          </div>
        </div>
      </div>

      {/* Report Contents Info */}
      <div className="bg-slate-800/60 border border-slate-700 rounded-xl p-4 mb-4 flex-shrink-0">
        <p className="text-xs text-slate-400 mb-3 uppercase tracking-widest">Report Contents</p>
        <div className="space-y-2">
          {[
            '🗺️ Detection summary & map coordinates',
            '⚠️ Risk analysis & danger level',
            '🤖 AI recommendations',
            '💥 Impact assessment',
            '📊 Timeline of events',
          ].map((item) => (
            <div key={item} className="flex items-center gap-2 text-xs text-slate-300">
              <CheckCircle2 size={11} className="text-emerald-400 flex-shrink-0" />
              {item}
            </div>
          ))}
        </div>
      </div>

      {/* Generate Button */}
      <div className="flex-shrink-0 mb-4">
        <motion.button
          whileTap={{ scale: 0.97 }}
          onClick={handleGenerate}
          disabled={isGenerating}
          className={`w-full py-3.5 rounded-xl font-bold text-sm flex items-center justify-center gap-2 transition-all ${
            isGenerating
              ? 'bg-slate-700 text-slate-500 cursor-not-allowed'
              : 'bg-gradient-to-r from-emerald-600 to-teal-600 text-white shadow-lg hover:shadow-emerald-500/20 hover:scale-[1.02]'
          }`}
        >
          {isGenerating ? (
            <><Loader2 size={16} className="animate-spin" /> Generating Report...</>
          ) : (
            <><FileText size={16} /> Generate Incident Report</>
          )}
        </motion.button>
      </div>

      {/* Report Output */}
      <AnimatePresence>
        {generated && report && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex-1 flex flex-col min-h-0"
          >
            <div className="flex items-center justify-between mb-2 flex-shrink-0">
              <div className="flex items-center gap-2">
                <CheckCircle2 size={14} className="text-emerald-400" />
                <span className="text-xs text-emerald-300 font-semibold">Report Generated</span>
              </div>
              <button
                onClick={handleDownload}
                className="flex items-center gap-1.5 text-xs bg-slate-800 hover:bg-slate-700 border border-slate-600 text-slate-300 px-3 py-1.5 rounded-lg transition-all"
              >
                <Download size={12} /> Download
              </button>
            </div>
            <div className="flex-1 overflow-y-auto bg-slate-900/80 border border-slate-700 rounded-xl p-4">
              <pre className="text-[11px] text-slate-300 leading-relaxed font-mono whitespace-pre-wrap">
                {report}
              </pre>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
